---
info:
  version: "2023-04-03T16:21:37Z"
  on: push
  title: "MyifElse"
host: "gn3fewkpqb.execute-api.us-east-2.amazonaws.com"
basePath: "/prod"
schemes:
- "https"
paths:
  /:
    get:
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
    post:
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
